@Host = https://localhost:7287
@ClinicId= c1d2b349-77f1-425d-a9f5-7137002c0d9f
@DoctorId= 2ffeff7f-273a-4caf-8915-f791d7643bc8
@PatientId = c1d2b349-77f1-425d-a9f5-7137002c0d95
@AppointmentId= 107b7271-c94b-4765-9f6b-b1b7b9c0036e

POST {{Host}}/appointments/{{AppointmentId}}/request-appointment
Content-Type: application/json
{
  "patientId": "{{PatientId}}"
}

### Cancel Request 
Put {{Host}}/appointments/{{AppointmentId}}/cancel-request
Content-Type: application/json
{
  "patientId": "{{PatientId}}"
}

### Cancel Appointment
Put {{Host}}/patients/{{PatientId}}/appointments/{{AppointmentId}}/cancel
Content-Type: application/json